import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Sans_3, Libre_Bodoni, Lora, Quicksand } from "next/font/google";
import "./ui/globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const LibreBodoniSerif = Libre_Bodoni({
  variable: "--font-libre-bodoni-serif",
  subsets: ["latin"],
});
const LoraSerif = Lora({
  variable: "--font-lora-serif",
  subsets: ["latin"],
});
const SourceSans3Sans = Source_Sans_3({
  variable: "--font-source-sans-3-sans",
  subsets: ["latin"],
});

const QuicksandSans = Quicksand({
  variable: "--font-Quicksand-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreBodoniSerif.variable} ${LoraSerif.variable} ${SourceSans3Sans.variable} ${QuicksandSans.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
