import type { Metadata } from "next";
import { Geist, Geist_Mono, Libre_Bodoni, Lora, Montserrat, Quicksand } from "next/font/google";
import "./ui/globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const LibreBodoniSansSerif = Libre_Bodoni({
  variable: "--font-libre-bodoni-sans-serif",
  subsets: ["latin"],
});
const LoraSansSerif = Lora({
  variable: "--font-lora-sans-serif",
  subsets: ["latin"],
});
const MontserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});
const QuicksandSans = Quicksand({
  variable: "--font-Quicksand-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreBodoniSansSerif.variable} ${LoraSansSerif.variable} ${MontserratSans.variable} ${QuicksandSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
