import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Sans_3, Libre_Bodoni, Lora, Quicksand, Cinzel } from "next/font/google";
import "@/_ui/globals.css";
import SonnerToaster from "@/_ui/ToasterSonner"

// This is the provider for the nextui library
// I am using this lib to be able to use the "date-input" component from the nextui library
import { NextUIProvider } from "@nextui-org/system";
import { Suspense } from "react";

const LibreBodoniSerif = Libre_Bodoni({
    variable: "--font-libre-bodoni-serif",
    subsets: ["latin"],
});
const CinzelSerif = Cinzel({
    variable: "--font-cinzel-serif",
    subsets: ["latin"],
});
// const LoraSerif = Lora({
//     variable: "--font-cinzel-serif",
//     subsets: ["latin"],
// });
const SourceSans3Sans = Source_Sans_3({
    variable: "--font-source-sans-3-sans",
    subsets: ["latin"],
});

const QuicksandSans = Quicksand({
    variable: "--font-Quicksand-sans",
    subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'ar' }]
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ lang: 'en' | 'ar' }>
}>) {

    // const locale = await params
    // console.log("locale.lang", locale.lang)
    // console.log("locale.lang", locale.lang === 'ar')

    return (
        <html lang={"en"} dir={"ltr"}>
            <body
                className={`${LibreBodoniSerif.variable} ${CinzelSerif.variable} ${SourceSans3Sans.variable} ${QuicksandSans.variable} antialiased `}
            >
                {/* 
        This is the provider for the nextui library
        I am using this lib to be able to use the "date-input" component from the nextui library 
        */}
                <NextUIProvider>
                    <main>
                        <Suspense >
                            {children}
                        </Suspense>
                    </main>
                    <SonnerToaster />
                </NextUIProvider>
            </body>
        </html>

    );
}
